### ISSUE TITLE
"Load on start up" options do not load application at start up of system !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.ksnip.ksnip#1]
Hi. 1st I would like to thank you too much for shipping this cute application for Linux users as flatpak on FlatHub ...

But unfortunately, there are many issues & I'm afraid they are due to limitation of flatpak ...... 

The application has in it's settings | Applications | 2 options checked by default & including "load on start up":
- remember ksnip position on move & load on start up
- remember ksnip tool selection & load on start up

But ksnip does not load on start up of OS when power laptop ON !

**Comment by DamirPorobic** [comment]
Sorry for the confusion, ksnip does not start up by itself, those two option mean basically the start of ksnip, you can read them as: 

- remember ksnip position on move & load when ksnip starts
- remember ksnip tool selection & load when ksnip starts

Please for future issue open them on the application repo https://github.com/ksnip/ksnip

**Comment by Nokia808** [comment]
@DamirPorobic 
Please correct them in ksnip UI in next version !
