### ISSUE TITLE
Global hot keys not working at all if application minimized to try icon !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.ksnip.ksnip#2]
Hi.

As the title saying. All hot keys NEVER working if ksnip is already lunched unless it is not minimized to try icon. If ksnip minimized to try icon, then no any of these global hot keys working at all inspite the fact that they are enabled by default !

Is this normal behaviour ? Is it flatpak limitation ?

**Comment by DamirPorobic** [comment]
I have logged for you a new issue here https://github.com/ksnip/ksnip/issues/392
