### ISSUE TITLE
Certain global hotkeys not working EVEN if ksnip NOT minimized to try icon !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.ksnip.ksnip#3]
Hi.

Please refer 1st to issue #2 

I noticed that even if ksnip not minimized to try icon, not all activated global hot key working !

The defected global hot keys are:
1) Alt+Shift+R
2) Alt+Shift+C
inspite the fact that these global hot keys are enabled by default ....

**Comment by DamirPorobic** [comment]
Please refer to https://github.com/ksnip/ksnip/issues/392
