### ISSUE TITLE
"Cupture Window under courser" global hot key option not active & can not activated !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.ksnip.ksnip#4]
Hi.

As the title saying - see screenshot bellow (look for what I set on it red arrow by "nomacs" program):

![screenshot](https://user-images.githubusercontent.com/25375330/88975585-f6320280-d2a9-11ea-9d7a-46de98ecd17e.png)

**Comment by DamirPorobic** [comment]
This means it's not supported for your image grabber, this is supposed to be so. Not all image grabber support everything. I believe this option is only supported for Plasma Wayland as you can see here https://github.com/ksnip/ksnip#supported-screenshot-types
